"""Faytuna Emergent Flow: transport of latent dynamical structure.

The public API is deliberately expressed in terms of traces, geometry, flow
operators, and tensor schemas. It does not assume a particular model library.
"""

from .types import (
    AlignmentResult,
    BifurcationPoint,
    CapabilityMatrix,
    CapacityDiagnostics,
    DepthTransferReport,
    FlowFitResult,
    FlowOperator,
    GapInterval,
    Probe,
    ProbeSplit,
    SurgeryPlan,
    TensorTransitionMapping,
    TrajectoryTrace,
    ValidationReport,
)
from .observation import ObservationProtocol, probe_fingerprint
from .geometry import (
    compute_frobenius_dissimilarity,
    dissimilarity_gain_schedule,
    evaluate_dynamic_alignment,
    fit_alignment,
    fit_depth_conditioned_alignment,
    fit_dynamic_depth_conditioned_alignment,
    project_teacher_weight,
    select_dynamic_depth_conditioned_alignment,
)
from .flow import calibrate_flow_confidence, fit_flow_transfer
from .forensics import FORENSIC_SCHEMA, audit_flow_fit, operator_fingerprint
from .solver import TrustRegionConfig, solve_flow_correction
from .surgery import QuadraticSurgeryCallback
from .connectors import CapabilityError, HFLikeConnector, SyntheticConnector, TorchConnector, TorchHooks
from .probes import ProbeGenerator, ProbeGeneratorConfig, PythonProbeGenerator
from .validation import intervene_flow, intervene_trace, rollout_intervention, validate_causal_transfer
from .signatures import DifferentialSignature, PathSignature, TangentTransport, differential_signature, fit_tangent_transport, multi_scale_path_signature
from .ablations import AblationCase, AblationReport, run_transfer_ablations
from .scorecard import SCORECARD_SCHEMA, ScorecardEntry, ScorecardReport, fit_target_operator, run_transfer_scorecard
from .jets import LocalJetTransport, fit_rank_aware_local_jet_transport
from .gpt2 import (
    GPT2Connector,
    GPT2ActivationCaptureResult,
    GPT2ActivationHookCapture,
    GPT2ProbePolicy,
    GPT2TensorLiftMapping,
    apply_gpt2_surgery,
    build_gpt2_teacher_flow_activation_targets,
    build_gpt2_surgery_plan,
    export_gpt2_checkpoint,
    export_gpt2_checkpoint_pair,
    fit_gpt2_conv1d_activation_least_squares,
    capture_gpt2_conv1d_activations,
    compute_gpt2_static_weight_dissimilarity,
    compute_universal_static_weight_dissimilarity,
    estimate_pilot_pulse_gain_bound,
    gpt2_depth_gain_weight,
    make_gpt2_hooks,
    make_gpt2_probe_splits,
    make_gpt2_python_probe_splits,
)
from .model_families import (
    GPT2_XL_TO_SMALL,
    MODEL_FAMILY_PRESETS,
    ModelFamilyPreset,
    ModelVariantSpec,
    TransformerArchitecture,
    generate_universal_mapping,
    get_model_family_preset,
    inspect_transformer_architecture,
    preflight_gpt2_pair,
)
from .runtime import LlamaCppValidationPlan, build_gguf_conversion_command, build_stock_llama_cpp_plan, preflight_stock_runtime, run_stock_llama_cpp_validation
from .adaptive_transfer import AdaptiveStep, AdaptiveTransferPolicy, AdaptiveTransferReport, run_adaptive_transfer, run_gpt2_weight_tune, run_universal_flow_tune
from .assessor import CorrectionAssessment, assess_correction
from .journal import ExperimentJournal, JOURNAL_SCHEMA, describe_model, journal_adaptive, journal_flow_fit, journal_math_profile, journal_preflight, journal_runtime, journal_scorecard, journal_surgery, journal_traces, strict_json_value
from .math_profile import MATH_COMPONENTS, build_math_profile, compare_math_profiles, resolve_math_components
from .pipeline import TraceBundle, collect_staged_synthetic, collect_staged_synthetic_splits, collect_synthetic_pair, collect_synthetic_pair_splits, fit_bundle, load_bundle, save_bundle
from .synthetic import QuadraticResidualSystem
from .scalable import DEFAULT_MAX_DENSE_FEATURES, DEFAULT_SCALABLE_RANK, data_aware_chart_projection, dense_memory_estimate, deterministic_chart_projection, fit_scalable_flow_transfer, requires_scalable_backend
from .benchmark import BenchmarkConfig, memory_snapshot, run_benchmark
from .knots import (
    PieceReport,
    build_attention_detour_projector,
    compute_subspace_entropy,
    fit_piecewise_mlp_with_retries,
    is_knot_subspace,
)
from .transformer_core import (
    TransformerConnector,
    TransformerActivationCaptureResult,
    TransformerActivationHookCapture,
    TransformerProbePolicy,
    TransformerTensorLiftMapping,
    apply_transformer_surgery,
    build_transformer_flow_activation_targets,
    build_transformer_surgery_plan,
    capture_transformer_activations,
    export_transformer_checkpoint,
    export_transformer_checkpoint_pair,
    fit_transformer_activation_least_squares,
    transformer_depth_gain_weight,
)
from .layer_streaming import (
    PipelinedLayerStreamer,
    StreamOutput,
    apply_gated_deltanet_patch,
    patched_chunk_gated_delta_rule,
    resolve_execution_device,
    stream_hidden_states,
)

__all__ = [
    "AlignmentResult",
    "BifurcationPoint",
    "CapabilityMatrix",
    "CapacityDiagnostics",
    "DepthTransferReport",
    "FlowFitResult",
    "FlowOperator",
    "HFLikeConnector",
    "CapabilityError",
    "GapInterval",
    "ObservationProtocol",
    "probe_fingerprint",
    "Probe",
    "ProbeGenerator",
    "ProbeGeneratorConfig",
    "PythonProbeGenerator",
    "ProbeSplit",
    "SurgeryPlan",
    "TensorTransitionMapping",
    "TrajectoryTrace",
    "TrustRegionConfig",
    "QuadraticSurgeryCallback",
    "ValidationReport",
    "FlowOperator",
    "fit_alignment",
    "fit_depth_conditioned_alignment",
    "fit_dynamic_depth_conditioned_alignment",
    "evaluate_dynamic_alignment",
    "select_dynamic_depth_conditioned_alignment",
    "compute_frobenius_dissimilarity",
    "dissimilarity_gain_schedule",
    "project_teacher_weight",
    "calibrate_flow_confidence",
    "fit_flow_transfer",
    "FORENSIC_SCHEMA",
    "audit_flow_fit",
    "operator_fingerprint",
    "PathSignature",
    "DifferentialSignature",
    "TangentTransport",
    "multi_scale_path_signature",
    "differential_signature",
    "fit_tangent_transport",
    "AblationCase",
    "AblationReport",
    "run_transfer_ablations",
    "SCORECARD_SCHEMA",
    "ScorecardEntry",
    "ScorecardReport",
    "run_transfer_scorecard",
    "fit_target_operator",
    "LocalJetTransport",
    "fit_rank_aware_local_jet_transport",
    "GPT2Connector",
    "GPT2ActivationCaptureResult",
    "GPT2ActivationHookCapture",
    "GPT2ProbePolicy",
    "GPT2TensorLiftMapping",
    "make_gpt2_hooks",
    "make_gpt2_probe_splits",
    "make_gpt2_python_probe_splits",
    "export_gpt2_checkpoint",
    "build_gpt2_surgery_plan",
    "build_gpt2_teacher_flow_activation_targets",
    "apply_gpt2_surgery",
    "export_gpt2_checkpoint_pair",
    "fit_gpt2_conv1d_activation_least_squares",
    "capture_gpt2_conv1d_activations",
    "compute_gpt2_static_weight_dissimilarity",
    "compute_universal_static_weight_dissimilarity",
    "estimate_pilot_pulse_gain_bound",
    "gpt2_depth_gain_weight",
    "GPT2_XL_TO_SMALL",
    "MODEL_FAMILY_PRESETS",
    "ModelFamilyPreset",
    "ModelVariantSpec",
    "TransformerArchitecture",
    "inspect_transformer_architecture",
    "generate_universal_mapping",
    "get_model_family_preset",
    "preflight_gpt2_pair",
    "LlamaCppValidationPlan",
    "build_gguf_conversion_command",
    "build_stock_llama_cpp_plan",
    "preflight_stock_runtime",
    "run_stock_llama_cpp_validation",
    "AdaptiveTransferPolicy",
    "AdaptiveStep",
    "AdaptiveTransferReport",
    "run_adaptive_transfer",
    "run_gpt2_weight_tune",
    "run_universal_flow_tune",
    "CorrectionAssessment",
    "assess_correction",
    "ExperimentJournal",
    "JOURNAL_SCHEMA",
    "describe_model",
    "journal_adaptive",
    "journal_flow_fit",
    "journal_math_profile",
    "journal_preflight",
    "journal_runtime",
    "journal_scorecard",
    "journal_surgery",
    "journal_traces",
    "strict_json_value",
    "MATH_COMPONENTS",
    "build_math_profile",
    "compare_math_profiles",
    "resolve_math_components",
    "TraceBundle",
    "collect_synthetic_pair",
    "collect_staged_synthetic",
    "collect_synthetic_pair_splits",
    "collect_staged_synthetic_splits",
    "fit_bundle",
    "save_bundle",
    "load_bundle",
    "intervene_flow",
    "intervene_trace",
    "rollout_intervention",
    "solve_flow_correction",
    "SyntheticConnector",
    "TorchConnector",
    "TorchHooks",
    "validate_causal_transfer",
    "QuadraticResidualSystem",
    "DEFAULT_MAX_DENSE_FEATURES",
    "DEFAULT_SCALABLE_RANK",
    "dense_memory_estimate",
    "deterministic_chart_projection",
    "data_aware_chart_projection",
    "fit_scalable_flow_transfer",
    "requires_scalable_backend",
    "BenchmarkConfig",
    "memory_snapshot",
    "run_benchmark",
    "PieceReport",
    "build_attention_detour_projector",
    "compute_subspace_entropy",
    "fit_piecewise_mlp_with_retries",
    "is_knot_subspace",
    "TransformerConnector",
    "TransformerActivationCaptureResult",
    "TransformerActivationHookCapture",
    "TransformerProbePolicy",
    "TransformerTensorLiftMapping",
    "apply_transformer_surgery",
    "build_transformer_flow_activation_targets",
    "build_transformer_surgery_plan",
    "capture_transformer_activations",
    "export_transformer_checkpoint",
    "export_transformer_checkpoint_pair",
    "fit_transformer_activation_least_squares",
    "transformer_depth_gain_weight",
    "PipelinedLayerStreamer",
    "StreamOutput",
    "apply_gated_deltanet_patch",
    "patched_chunk_gated_delta_rule",
    "resolve_execution_device",
    "stream_hidden_states",
]
